### ISSUE TITLE
any illustration or showcase??

### ISSUE THREAD

**Issue by goyalyashpal** [nhawkes/vscode-selection-overtype#1]
https://github.com/nhawkes/vscode-selection-overtype/blob/1195639e0e518485a5fe8ec21c262eef8d2fd756/README.md?plain=1#L3

hi, i am having trouble understanding what this means and hence, what this extension does. can u add a more illustrative example?

**Comment by nhawkes** [comment]
The gif should explain it better. We manage to replace both `integer` and `setInteger` preserving the cases

**Comment by goyalyashpal** [comment]
there were no gifs loaded

**Comment by nhawkes** [comment]
https://github.com/nhawkes/vscode-selection-overtype/blob/1195639e0e518485a5fe8ec21c262eef8d2fd756/README.md?plain=1#L7

https://github.com/nhawkes/vscode-selection-overtype/blob/master/images/demo.gif

**Comment by goyalyashpal** [comment]
i dont know what the problem is, github aint loading binary files on my device*s* for several months now

**Comment by goyalyashpal** [comment]
![image](https://github.com/nhawkes/vscode-selection-overtype/assets/19423063/7865862a-d325-44fd-9bb6-2587242291e4)


not to imply that illustrations don't exist, just that they aren't working on my side - and probably many other users too... i am closing this as not planned. don't take it to heart.

**Comment by goyalyashpal** [comment]
* closing as https://github.com/orgs/community/discussions/69838#discussioncomment-7286770
